name: Node.js end-to-end

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  build:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying
        run: echo "Deploying application..."

      - name: Restarting Server
        run: echo "Restarting server..."
